#
# Runs the regressions at the CBG and city level. Note: Uses the aprs_regression
# file that is generated by the script src/Appendix/J_IncomeDisparity/geocode_aprs.R
#

library(tidyverse)
library(ggplot2)
library(tigris)
library(gtools)
library(censusapi)

Sys.setenv(CENSUS_KEY="INSERT CENSUS KEY HERE")

# Parameters
ACS_year <- 2016

# 1. Load data ----------------
# Load number of ADUs per CBG (n)
aprs_regression <- read.csv(
  paste0("data/processed/City-analysis/aprs_regression", ACS_year, ".csv"), 
  colClasses=c("CBG"="character"))

# 2. Add other CBG-level variables -----------------
options(tigris_use_cache = TRUE)
counties <- counties("CA", year=ACS_year)

other_cbg <- counties$COUNTYFP %>% 
  map_dfr(function(county){
    
    print(county)
    
    age_income <- getCensus(
      name = "acs/acs5",
      vintage = ACS_year,
      region = "block group:*",
      regionin = paste0("state:06+county:",county),
      vars = c(
        "B19013_001E", # HH Median income 
        "B19001_001E", # Number of households
        "B25035_001E", # Estimate: Median year structure built
        "B25064_001E", # Median gross rent (dollars)
        "B25058_001E" # Median contract rent (dollars)
        )
    ) %>% 
      transmute(
        CBG =
          paste0(state,county,tract,block_group),
        hh = B19001_001E,
        hhmedinc = ifelse(B19013_001E < 0, NA, B19013_001E),
        med_year_built = ifelse(B25035_001E < 0, NA, B25035_001E),
        med_gross_rent = ifelse(B25064_001E < 0, NA, B25064_001E),
        med_contract_rent = ifelse(B25058_001E < 0, NA, B25058_001E)
      )
  })

# Consolidate
aprs_regression <- aprs_regression %>% 
  left_join(other_cbg, by = 'CBG') %>%
  dplyr::mutate(hhmedian_inc_10k = hhmedinc / 10000)

# Drop CBGs that do not belong to any city
reg_df <- aprs_regression %>% dplyr::filter(!is.na(NAME))

colSums(is.na(reg_df))

# 3. Regressions ------------------------
reg_df <- reg_df %>% dplyr::mutate(l_name = tolower(NAME))

run_city_regression <- function(f, data) {
  city_df <- data.frame()
  for (city in unique(data$NAME)) {
    city_data <- data %>% filter(NAME == city)
    if (dim(city_data)[1] < 10) next
    m <- lm(f, data = city_data)
    city_beta <- coef(m)['hhmedian_inc_10k']
    if (is.na(city_beta)) next
    city_pval <- summary(m)$coefficients['hhmedian_inc_10k', 'Pr(>|t|)']
    
    city_df <- rbind(city_df, data.frame(city=city, beta=city_beta, pval=city_pval))
  }
  return(city_df)
}

# n ~ hhmedian_inc_10k + hh
hh.df <- run_city_regression(f=formula('n ~ hhmedian_inc_10k + hh'), data=reg_df)

# n ~ hhmedian_inc_10k + hh + med_year_built
built.df <- run_city_regression(f=formula('n ~ hhmedian_inc_10k + hh + med_year_built'), data=reg_df)
